- hosts: raspberry
  remote_user: pi
  become: yes
  tasks:
  - name: "install apt package"
    apt :
      name : "{{item}}"
    with_items:
      - git
      - gcc
      - make
      - openssl
      - libssl-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      # - npm
      # - libavahi-compat-libdnssd-dev


  - name: "put pyenv"
    become_user: pi
    git :
      repo: "git://github.com/yyuu/pyenv.git"
      dest: "/home/pi/.pyenv"
  # todo : install & setting python 3.6.3


  - name: "set timezone"
    timezone:
      name: Asia/Tokyo

  - name: "deploy discord bots"
    become_user: pi
    git:
      repo: "git://github.com/deneeeeeeb/discordbot.git"
      dest: "/home/pi/discordbot"
     

  - name: "deploy home-voice"
    become_user: pi
    git:
      repo: "git://github.com/deneeeeeeb/home-voice.git"
      dest: "/home/pi/home-voice/git"



  roles:
    - file_copy
