- name : "copy files"
  become_user: pi
  copy :
    src  : "{{item}}"
    dest : "/{{item}}"

  with_items :
    - home/pi/.bashrc
    - home/pi/home-voice/node_modules/mdns/lib/browser.js
    - home/pi/etc/
    - home/pi/etc/token.conf
